package com.beamUp.request;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;

@Builder
@NoArgsConstructor
@AllArgsConstructor
@Data
public class BeamUrlRequest {

    @NotNull
    @NotEmpty
    private String url;

    // if empty, it will be generated by system
    private String code;

}
